name: health_bridge
description: Read and write health data from Apple HealthKit and Google Health Connect.
version: 2.0.0
repository: https://github.com/ytsni/health_bridge
issue_tracker: https://github.com/ytsni/health_bridge/issues

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter
  intl: '>=0.18.0 <0.21.0'
  device_info_plus: '>=12.1.0 <14.0.0'
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  json_serializable: any
  mocktail: ^1.0.4
  mockito: ^5.4.5

flutter:
  plugin:
    platforms:
      android:
        package: cachet.plugins.health
        pluginClass: HealthPlugin
      ios:
        pluginClass: HealthPlugin
